# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # Enable version updates for Maven dependencies
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Jeremy-Heer"
    assignees:
      - "Jeremy-Heer"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "Jeremy-Heer"
    assignees:
      - "Jeremy-Heer"
    commit-message:
      prefix: "ci"
      include: "scope"