name: Build and Release on Tag

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required for creating releases
      packages: write  # Required if publishing to GitHub packages
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0  # Fetch full history for proper versioning
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Extract version from tag
      run: |
        echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
    
    - name: Update pom.xml version
      run: |
        mvn versions:set -DnewVersion=${{ env.VERSION }}
        mvn versions:commit
    
    - name: Run tests
      run: mvn clean test
    
    - name: Build application
      run: mvn clean package -DskipTests
    
    - name: Verify JAR file
      run: |
        ls -la target/*.jar
        echo "JAR_FILE=$(ls target/*.jar | grep -v original | head -1)" >> $GITHUB_ENV
    
    - name: Create Release Notes
      run: |
        echo "# Release ${{ env.TAG_VERSION }}" > release-notes.md
        echo "" >> release-notes.md
        echo "## Changes" >> release-notes.md
        echo "Built from commit: ${{ github.sha }}" >> release-notes.md
        echo "" >> release-notes.md
        echo "## Artifacts" >> release-notes.md
        echo "- scim2-server JAR file" >> release-notes.md
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG_VERSION }}
        name: Release ${{ env.TAG_VERSION }}
        body_path: release-notes.md
        draft: false
        prerelease: false
        files: |
          ${{ env.JAR_FILE }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Tag:** ${{ env.TAG_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Version:** ${{ env.VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **JAR:** $(basename ${{ env.JAR_FILE }})" >> $GITHUB_STEP_SUMMARY
        echo "- **Java:** 17 (Temurin)" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Tool:** Maven" >> $GITHUB_STEP_SUMMARY